version: '3.5'
services:
  server:
    build: ./
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: mongo:3.6.10
    volumes:
      - ./db-data:/data/db
    ports:
        - "27017"

